### PR TITLE
Minor corrections to text

### PR DESCRIPTION
**Pull request by mfluehr**

### CODE REVIEW

**Comment by acabal** [comment]
We probably removed italics from `genus` because it's a regular English word now. Is it being used here in the sense of `genus and species` or in some other sense?

**Comment by mfluehr** [comment]
> Is it being used here in the sense of `genus and species` or in some other sense?

I honestly don't know. I was expecting the word "genius" here, which is why I looked it up in the first place, and discovered the original text has the word "genus" italicized.

I like the italics because it draws attention to the odd use of the word. The speaker is supposed to be a dimwit, so maybe the fact that she says "genus" instead of "genius" is meant to humorously underline that. Nevertheless, I don't know if that's part of the author's original intent. I'll accept whatever editorial call you want to make here.

**Comment by acabal** [comment]
OK. In that case, can you make it `<em>` and not `<i>`? Please edit the commit in this PR so we don't add more commits. Thanks!

**Comment by acabal** [comment]
Can you just replace your earlier italics commit with the em commit, so we only have 2 commits in this PR?

**Comment by mfluehr** [comment]
I squashed the two italics commits together, and also fixed a couple more typos.

**Comment by acabal** [comment]
Thanks!

**Pull request merged**
